package de.siphalor.jcyo.core.impl.transform;

import de.siphalor.jcyo.core.api.import_order.ImportOrder;
import de.siphalor.jcyo.core.api.import_order.ImportOrderElement;
import de.siphalor.jcyo.core.impl.CommentStyle;
import de.siphalor.jcyo.core.impl.stream.PeekableTokenStream;
import de.siphalor.jcyo.core.impl.stream.TokenStream;
import de.siphalor.jcyo.core.impl.token.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class JcyoImportReordererTest {
	JcyoImportReorderer reorderer;

	@BeforeEach
	void setUp() {
		reorderer = new JcyoImportReorderer(ImportOrder.ofElements(List.of(
				new ImportOrderElement.Prefix("com.example", false),
				new ImportOrderElement.Prefix("org.example", false),
				ImportOrderElement.blankLine(),
				new ImportOrderElement.Prefix("java", false),
				ImportOrderElement.blankLine(),
				ImportOrderElement.normalRest(),
				ImportOrderElement.blankLine(),
				ImportOrderElement.staticRest()
		)));
	}

	@Test
	void simpleTokens() {
		var result = reorderer.apply(PeekableTokenStream.from(TokenStream.from(List.of(
				new JavaKeywordToken(JavaKeyword.PACKAGE),
				new WhitespaceToken(' '),
				new IdentifierToken("blub"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.STATIC),
				new WhitespaceToken(' '),
				new IdentifierToken("java"),
				new OperatorToken('.'),
				new IdentifierToken("util"),
				new OperatorToken('.'),
				new IdentifierToken("Objects"),
				new OperatorToken('.'),
				new IdentifierToken("requireNonNull"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("java"),
				new OperatorToken('.'),
				new IdentifierToken("util"),
				new OperatorToken('.'),
				new IdentifierToken("List"),
				new OperatorToken(';'),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new JavaKeywordToken(JavaKeyword.IF),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.FALSE),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("org"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("ZZZ"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new IdentifierToken("end"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("com"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Test"),
				new OperatorToken(';'),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("org"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Test"),
				new OperatorToken(';'),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("com"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Abc"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.PUBLIC),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.CLASS),
				new OperatorToken('{'),
				new OperatorToken('}'),
				EofToken.instance()
		))));

		assertThat(result.stream().toList()).isEqualTo(List.of(
				new JavaKeywordToken(JavaKeyword.PACKAGE),
				new WhitespaceToken(' '),
				new IdentifierToken("blub"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("com"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Abc"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("com"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Test"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("org"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Test"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new JavaKeywordToken(JavaKeyword.IF),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.FALSE),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("org"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("ZZZ"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new IdentifierToken("end"),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("java"),
				new OperatorToken('.'),
				new IdentifierToken("util"),
				new OperatorToken('.'),
				new IdentifierToken("List"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.STATIC),
				new WhitespaceToken(' '),
				new IdentifierToken("java"),
				new OperatorToken('.'),
				new IdentifierToken("util"),
				new OperatorToken('.'),
				new IdentifierToken("Objects"),
				new OperatorToken('.'),
				new IdentifierToken("requireNonNull"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.PUBLIC),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.CLASS),
				new OperatorToken('{'),
				new OperatorToken('}')
		));
	}

	@Test
	void siblingDirectives() {
		var result = reorderer.apply(PeekableTokenStream.from(TokenStream.from(List.of(
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.STATIC),
				new WhitespaceToken(' '),
				new IdentifierToken("java"),
				new OperatorToken('.'),
				new IdentifierToken("util"),
				new OperatorToken('.'),
				new IdentifierToken("Objects"),
				new OperatorToken('.'),
				new IdentifierToken("requireNonNull"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new JavaKeywordToken(JavaKeyword.IF),
				new WhitespaceToken(' '),
				new IdentifierToken("abc"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("java"),
				new OperatorToken('.'),
				new IdentifierToken("util"),
				new OperatorToken('.'),
				new IdentifierToken("Objects"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new IdentifierToken("elif"),
				new WhitespaceToken(' '),
				new IdentifierToken("def"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("org"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Example"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.CLASS),
				new WhitespaceToken(' '),
				new IdentifierToken("Blub"),
				new OperatorToken('{'),
				new OperatorToken('}'),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new JavaKeywordToken(JavaKeyword.ELSE),
				new LineBreakToken("\n"),
				new PlainJavaCommentToken("// This is a test\n", CommentStyle.LINE, false),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new IdentifierToken("end"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new IdentifierToken("com"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Test"),
				new OperatorToken(';'),
				new PlainJavaCommentToken("// Ending this file", CommentStyle.LINE, false)
		))));

		assertThat(result.stream().toList()).isEqualTo(List.of(
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new IdentifierToken("com"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Test"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new JavaKeywordToken(JavaKeyword.IF),
				new WhitespaceToken(' '),
				new IdentifierToken("abc"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("java"),
				new OperatorToken('.'),
				new IdentifierToken("util"),
				new OperatorToken('.'),
				new IdentifierToken("Objects"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new IdentifierToken("elif"),
				new WhitespaceToken(' '),
				new IdentifierToken("def"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new IdentifierToken("org"),
				new OperatorToken('.'),
				new IdentifierToken("example"),
				new OperatorToken('.'),
				new IdentifierToken("Example"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.CLASS),
				new WhitespaceToken(' '),
				new IdentifierToken("Blub"),
				new OperatorToken('{'),
				new OperatorToken('}'),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new JavaKeywordToken(JavaKeyword.ELSE),
				new LineBreakToken("\n"),
				new PlainJavaCommentToken("// This is a test\n", CommentStyle.LINE, false),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new IdentifierToken("end"),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.IMPORT),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.STATIC),
				new WhitespaceToken(' '),
				new IdentifierToken("java"),
				new OperatorToken('.'),
				new IdentifierToken("util"),
				new OperatorToken('.'),
				new IdentifierToken("Objects"),
				new OperatorToken('.'),
				new IdentifierToken("requireNonNull"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new PlainJavaCommentToken("// Ending this file", CommentStyle.LINE, false)
		));
	}

	@Test
	void noImports() {
		List<Token> tokens = List.of(
				new JavaKeywordToken(JavaKeyword.PACKAGE),
				new WhitespaceToken(' '),
				new IdentifierToken("test"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JavaKeywordToken(JavaKeyword.CLASS),
				new WhitespaceToken(' '),
				new IdentifierToken("Test"),
				new OperatorToken('{'),
				new OperatorToken('}')
		);

		var result = reorderer.apply(PeekableTokenStream.from(TokenStream.from(tokens)));
		assertThat(result.stream().toList()).isEqualTo(tokens);
	}

	@Test
	void noImportsWithDirectives() {
		List<Token> tokens = List.of(
				new JavaKeywordToken(JavaKeyword.PACKAGE),
				new WhitespaceToken(' '),
				new IdentifierToken("test"),
				new OperatorToken(';'),
				new LineBreakToken("\n"),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new JavaKeywordToken(JavaKeyword.IF),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.FALSE),
				new LineBreakToken("\n"),
				new WhitespaceToken('\t'),
				new JavaKeywordToken(JavaKeyword.CLASS),
				new WhitespaceToken(' '),
				new IdentifierToken("Test"),
				new OperatorToken('{'),
				new LineBreakToken("\n"),
				new WhitespaceToken('\t'),
				new PlainJavaCommentToken("// This is a test\n", CommentStyle.LINE, false),
				new WhitespaceToken('\t'),
				new JavaKeywordToken(JavaKeyword.IF),
				new WhitespaceToken(' '),
				new JavaKeywordToken(JavaKeyword.TRUE),
				new LineBreakToken("\n"),
				new WhitespaceToken('\t'),
				new WhitespaceToken('\t'),
				new PlainJavaCommentToken("// This another comment\n", CommentStyle.LINE, false),
				new WhitespaceToken('\t'),
				new WhitespaceToken('\t'),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new JavaKeywordToken(JavaKeyword.ELSE),
				new LineBreakToken("\n"),
				new WhitespaceToken('\t'),
				new WhitespaceToken('\t'),
				new PlainJavaCommentToken("// else branch\n", CommentStyle.LINE, false),
				new WhitespaceToken('\t'),
				new WhitespaceToken('\t'),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new IdentifierToken("end"),
				new LineBreakToken("\n"),
				new WhitespaceToken('\t'),
				new OperatorToken('}'),
				new LineBreakToken("\n"),
				new JcyoDirectiveStartToken("//#", CommentStyle.LINE),
				new IdentifierToken("end"),
				new LineBreakToken("\n")
		);

		var result = reorderer.apply(PeekableTokenStream.from(TokenStream.from(tokens)));
		assertThat(result.stream().toList()).isEqualTo(tokens);
	}
}
